Upgrade ember-cli and improve tree-shacking
ef4/memory-scroll pull request #17
Opened 2017-12-31 21:31 UTC by villander

2018-01-02 17:32 UTC, ef4 requested changes
Thanks, I left a couple small bits of feedback.

Also, as an aesthetic comment, I don't personally like `const` for local variables that only happen to not be mutated at the moment. I realize this is an endless bikeshed and I wouldn't block the PR for just that. 

But my thought process is: would it *necessarily* be wrong for some future editor of the code to mutate the variable? If not, then it should really be `let`. `const` is communicating something too strong to future readers.

2018-01-02 17:32 UTC, ef4 commented on app/transitions.js
> +}
This file doesn't belong in an addon (if it exists at all it should be tests/dummy/app/transitions.js). That may be a bug in the liquid-fire generator.

2018-01-02 17:32 UTC, ef4 commented on .travis.yml
> -    - EMBER_TRY_SCENARIO=ember-lts-2.8
Let's keep the lts-2.8 test, there's no reason not to keep supporting it.

2018-01-02 17:32 UTC, ef4 commented on package.json
> +  "version": "0.0.0",
we lost our version number here

2018-02-04 00:53 UTC, villander commented on .travis.yml
> -    - EMBER_TRY_SCENARIO=ember-lts-2.8
Ok

2018-02-04 00:53 UTC, villander commented on app/transitions.js
> +}
Ok

2018-02-04 00:54 UTC, villander commented on package.json
> +  "version": "0.0.0",
Ok

2018-02-04 20:20 UTC, villander commented
Done @ef4

2018-02-04 21:05 UTC, villander commented
Done @ef4

2018-02-12 12:04 UTC, villander commented
@ef4 we can do the merge this?

2018-03-28 23:13 UTC, merged